# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RU79sGwslwLgjk7mqBI6o2NrTv4C4qXD

models.py — Full AI Pipeline for Outbreak Detection System
Based on ward_data table in PostgreSQL

Models:
  1. Severity Scoring         (rule-based weighted score)
  2. Priority Queue Index     (linear formula)
  3. Hospital Recommender     (multi-factor scoring)
  4. Trend Analyzer           (moving avg + WoW growth)
  5. Outbreak Early Warning   (exp smoothing + z-score anomaly)
  6. Hotspot Zoning           (composite score + zone labels)
  7. Advisory Generator       (rule engine)
"""

import pandas as pd
import numpy as np
from datetime import date
from collections import defaultdict
import psycopg2
from psycopg2.extras import RealDictCursor
import os

# ─────────────────────────────────────────────────────────────
# DATABASE CONNECTION
# ─────────────────────────────────────────────────────────────

def get_db_connection():
    return psycopg2.connect(
        host=os.getenv("DB_HOST", "localhost"),
        database=os.getenv("DB_NAME", "health_app"),
        user=os.getenv("DB_USER", "postgres"),
        password=os.getenv("DB_PASSWORD", "password"),
        port=os.getenv("DB_PORT", "5432")
    )

# ─────────────────────────────────────────────────────────────
# LOAD DATA FROM DATABASE
# ─────────────────────────────────────────────────────────────

def load_ward_data():
    try:
        conn = get_db_connection()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute("SELECT * FROM ward_data ORDER BY ward")
            rows = cur.fetchall()
        conn.close()
        df = pd.DataFrame(rows)
    except Exception as e:
        print(f"Database connection failed: {e}. Using mock data.")
        # Mock data for testing
        mock_data = [
            {
                "ward": "Ward 1 - Shivajinagar",
                "syndrome": "respiratory",
                "hospital_load_pct": 85.0,
                "pmjay_coverage_pct": 75.0,
                "population_density": "high",
                "water_quality_issue": 0,
                "sanitation_score": 6,
                "nearest_hospital_km": 2.1,
                **{f"day{i}": max(0, 50 + (i-15)*2 + np.random.randint(-10, 10)) for i in range(1, 31)}
            },
            {
                "ward": "Ward 2 - Kothrud",
                "syndrome": "respiratory",
                "hospital_load_pct": 58.0,
                "pmjay_coverage_pct": 80.0,
                "population_density": "medium",
                "water_quality_issue": 0,
                "sanitation_score": 7,
                "nearest_hospital_km": 3.4,
                **{f"day{i}": max(0, 30 + (i-15)*1 + np.random.randint(-5, 5)) for i in range(1, 31)}
            },
            {
                "ward": "Ward 3 - Aundh",
                "syndrome": "gastrointestinal",
                "hospital_load_pct": 72.0,
                "pmjay_coverage_pct": 70.0,
                "population_density": "medium",
                "water_quality_issue": 1,
                "sanitation_score": 5,
                "nearest_hospital_km": 1.8,
                **{f"day{i}": max(0, 40 + (i-15)*1.5 + np.random.randint(-8, 8)) for i in range(1, 31)}
            }
        ]
        df = pd.DataFrame(mock_data)

    DAY_COLS = [f"day{i}" for i in range(1, 31)]

    # Density encoding for numeric ops
    DENSITY_MAP = {"high": 3, "medium": 2, "low": 1}
    df["density_score"] = df["population_density"].map(DENSITY_MAP)

    return df, DAY_COLS

# ═════════════════════════════════════════════════════════════
# Symptom aggregation (from `reports` table)
# ═════════════════════════════════════════════════════════════

def load_reports():
    """Load ward-level symptom weights from `reports` for city-wide + per-ward clustering."""
    try:
        conn = get_db_connection()
        with conn.cursor(cursor_factory=RealDictCursor) as cur:
            cur.execute("SELECT ward, symptoms FROM reports")
            rows = cur.fetchall()
        conn.close()
        return rows
    except Exception as e:
        print(f"Reports load failed: {e}. Using empty symptom aggregates.")
        return []


def normalize_symptom_value(v):
    # Accept numbers or booleans; ignore anything else.
    if v is None:
        return 0.0
    if isinstance(v, bool):
        return 1.0 if v else 0.0
    if isinstance(v, (int, float)):
        return float(v)
    try:
        return float(v)
    except Exception:
        return 0.0


def compute_symptom_aggregates(ward_names: list):
    """
    Returns:
      - top_symptoms: [{"name": str, "value": 0-100}, ...]
      - ward_symptoms: { wardName: [symptomName, ...], ... } (top 3)
    """
    city_counter = defaultdict(float)
    ward_counter = defaultdict(lambda: defaultdict(float))

    for row in load_reports():
        ward = row.get("ward")
        symptoms = row.get("symptoms") or {}
        if not isinstance(symptoms, dict):
            continue

        for symptom_name, raw_val in symptoms.items():
            weight = normalize_symptom_value(raw_val)
            if weight <= 0:
                continue
            city_counter[symptom_name] += weight
            if ward:
                ward_counter[ward][symptom_name] += weight

    city_sorted = sorted(city_counter.items(), key=lambda x: x[1], reverse=True)
    max_city = city_sorted[0][1] if city_sorted else 1.0

    top_symptoms = []
    for symptom_name, weight in city_sorted[:4]:
        # Normalize weights to 0..100 so UI bar widths are stable.
        value = int(round((weight / max_city) * 100))
        top_symptoms.append({"name": symptom_name, "value": value})

    # Per-ward top 3 with fallback to global top 3.
    global_top_names = [s["name"] for s in top_symptoms[:3]]
    ward_symptoms = {}
    for ward in ward_names:
        ward_sorted = sorted(
            ward_counter.get(ward, {}).items(),
            key=lambda x: x[1],
            reverse=True,
        )
        names = [name for name, _ in ward_sorted[:3]]
        if not names:
            names = global_top_names
        ward_symptoms[ward] = names

    return top_symptoms, ward_symptoms

# ═════════════════════════════════════════════════════════════
# MODEL 1 — Symptom Severity & Risk Scoring
# ═════════════════════════════════════════════════════════════
# Input:  symptoms dict, age, comorbidities list, duration
# Output: risk_score (0–100), severity class

SYMPTOM_WEIGHTS = {
    "breathlessness": 25,
    "high_fever":     20,
    "vomiting":       15,
    "joint_pain":     10,
    "rash":           10,
    "cough":          10,
    "diarrhea":        8,
    "nausea":          6,
    "fatigue":         5,
}

def severity_score(symptoms: dict, age: int, comorbidities: list, duration_days: int) -> dict:
    """
    symptoms      : {"fever": True, "cough": True, ...}
    comorbidities : [True, False, ...]  (diabetes, asthma, heart_disease, etc.)
    """
    score = sum(SYMPTOM_WEIGHTS.get(s, 0) for s, active in symptoms.items() if active)

    # Age risk
    if age >= 60:    score += 15
    elif age <= 5:   score += 12
    elif age >= 45:  score +=  5

    # Comorbidity load
    score += sum(1 for c in comorbidities if c) * 10

    # Duration multiplier
    if duration_days >= 5:
        score = score * 1.2

    score = min(round(score), 100)

    if score >= 60:   severity = "High"
    elif score >= 35: severity = "Moderate"
    else:             severity = "Mild"

    return {"risk_score": score, "severity": severity}

# ═════════════════════════════════════════════════════════════
# MODEL 2 — Priority Queue Index
# ═════════════════════════════════════════════════════════════
# Input:  risk_score, age, days_waiting
# Output: priority_index (higher = seen sooner)

def priority_index(risk_score: float, age: int, days_waiting: int) -> dict:
    age_risk  = 50 if (age >= 60 or age <= 5) else 25
    wait_norm = min(days_waiting / 7, 1.0) * 100

    index = (0.6 * risk_score) + (0.2 * age_risk) + (0.2 * wait_norm)
    index = round(index, 2)

    if index >= 70:   label = "Urgent"
    elif index >= 45: label = "Priority"
    else:             label = "Routine"

    return {"priority_index": index, "queue_label": label}

# ═════════════════════════════════════════════════════════════
# MODEL 3 — Hospital Recommender (PM-JAY aware)
# ═════════════════════════════════════════════════════════════
# Uses ward-level nearest_hospital_km and pmjay_coverage_pct from CSV
# Input:  patient dict, list of hospital dicts
# Output: ranked hospital list with scores

SAMPLE_HOSPITALS = [
    {"name": "KEM Hospital Pune",         "pmjay": True,  "specialties": ["respiratory","general"], "available_beds": 40, "total_beds": 120, "distance_km": 2.1},
    {"name": "Sassoon General Hospital",  "pmjay": True,  "specialties": ["vector_borne","general","respiratory"], "available_beds": 60, "total_beds": 200, "distance_km": 3.4},
    {"name": "Ruby Hall Clinic",          "pmjay": False, "specialties": ["respiratory","cardiac"], "available_beds": 15, "total_beds": 80,  "distance_km": 1.8},
    {"name": "Jehangir Hospital",         "pmjay": False, "specialties": ["gastrointestinal","general"], "available_beds": 20, "total_beds": 90,  "distance_km": 4.2},
    {"name": "Deenanath Mangeshkar",      "pmjay": True,  "specialties": ["gastrointestinal","vector_borne","respiratory"], "available_beds": 35, "total_beds": 150, "distance_km": 5.0},
    {"name": "Poona Hospital",            "pmjay": True,  "specialties": ["general","respiratory"], "available_beds": 50, "total_beds": 130, "distance_km": 2.7},
]

def score_hospital(hospital: dict, patient: dict) -> float:
    score = 0.0

    # Specialty match (hard requirement — skip if no match)
    if patient["needed_specialty"] not in hospital["specialties"]:
        return 0.0

    # Specialty match bonus
    score += 35

    # Capacity ratio
    cap_ratio = hospital["available_beds"] / hospital["total_beds"]
    score += cap_ratio * 25

    # Distance (closer = better, max 20 pts)
    dist_score = max(0, 10 - hospital["distance_km"]) * 2
    score += dist_score

    # PM-JAY match
    if patient.get("pmjay_beneficiary") and hospital["pmjay"]:
        score += 20

    return round(score, 2)

def recommend_hospitals(patient: dict, hospitals: list = SAMPLE_HOSPITALS, top_n: int = 3) -> list:
    scored = [(h, score_hospital(h, patient)) for h in hospitals]
    scored = [(h, s) for h, s in scored if s > 0]
    ranked = sorted(scored, key=lambda x: x[1], reverse=True)[:top_n]
    return [{"hospital": h["name"], "score": s, "pmjay": h["pmjay"], "beds_free": h["available_beds"]} for h, s in ranked]

# ═════════════════════════════════════════════════════════════
# MODEL 4 — Trend Analyzer
# ═════════════════════════════════════════════════════════════
# Input:  ward row from CSV
# Output: moving_avg, wow_growth_pct, 48hr_growth, seasonality_flag

def analyze_trends(daily_cases: list) -> dict:
    n = len(daily_cases)

    # 7-day moving average (last value)
    moving_avg_last = round(
        sum(daily_cases[max(0, n - 7):]) / min(7, n), 1
    )

    # Week-over-week growth
    wow_growth = None
    if n >= 14:
        this_week = sum(daily_cases[-7:])
        last_week = sum(daily_cases[-14:-7])
        if last_week > 0:
            wow_growth = round((this_week - last_week) / last_week * 100, 1)

    # 48-hour growth rate (last 2 days vs 2 days before)
    growth_48h = None
    if n >= 4:
        recent2 = daily_cases[-1] + daily_cases[-2]
        prior2  = daily_cases[-3] + daily_cases[-4]
        if prior2 > 0:
            growth_48h = round((recent2 - prior2) / prior2 * 100, 1)

    # Monsoon seasonality flag (India: June–October)
    month = date.today().month
    seasonality = "MONSOON_RISK" if 6 <= month <= 10 else "NORMAL"

    return {
        "moving_avg_7d":  moving_avg_last,
        "wow_growth_pct": wow_growth,
        "growth_48h_pct": growth_48h,
        "seasonality":    seasonality,
    }

# ═════════════════════════════════════════════════════════════
# MODEL 5 — Outbreak Early Warning (MAIN AI MODEL)
# ═════════════════════════════════════════════════════════════
# Stage A: Exponential smoothing → expected baseline
# Stage B: Z-score anomaly detection → outbreak probability
# Input:  ward_name, daily_cases list
# Output: zone (RED/YELLOW/GREEN), outbreak_prob, z_score, baseline

def exp_smooth(series: list, alpha: float = 0.3) -> list:
    smoothed = [series[0]]
    for i in range(1, len(series)):
        s = alpha * series[i] + (1 - alpha) * smoothed[-1]
        smoothed.append(round(s, 2))
    return smoothed

def forecast_next_n(smoothed: list, actual: list, n_days: int = 7) -> list:
    """Simple forward forecast using trend from last 3 days"""
    last = smoothed[-1]
    if len(actual) >= 3:
        trend = (actual[-1] - actual[-3]) / 2
    else:
        trend = 0
    forecast = []
    for _ in range(n_days):
        last = last * 0.7 + (last + trend) * 0.3
        forecast.append(max(0, round(last)))
    return forecast

def outbreak_warning(ward_name: str, daily_cases: list) -> dict:
    if len(daily_cases) < 7:
        return {"error": "Need at least 7 days"}

    # Stage A — baseline via exponential smoothing
    smoothed = exp_smooth(daily_cases)
    baseline = smoothed[-1]
    actual   = daily_cases[-1]

    # Stage B — z-score on last 7 days
    window   = daily_cases[-7:]
    mean     = np.mean(window)
    std      = np.std(window) if np.std(window) > 0 else 1.0
    z        = (actual - mean) / std

    # Sigmoid → outbreak probability
    prob = round(1 / (1 + np.exp(-z)) * 100, 1)

    # Zone classification
    if prob >= 75:   zone = "RED"
    elif prob >= 55: zone = "YELLOW"
    else:            zone = "GREEN"

    # 7-day forecast
    forecast = forecast_next_n(smoothed, daily_cases, n_days=7)

    return {
        "ward":          ward_name,
        "actual":        actual,
        "baseline":      round(baseline, 1),
        "z_score":       round(z, 3),
        "outbreak_prob": prob,
        "zone":          zone,
        "forecast_7d":   forecast,
    }

# ═════════════════════════════════════════════════════════════
# MODEL 6 — Hotspot Zoning
# ═════════════════════════════════════════════════════════════
# Input:  ward_results list (from Model 5) + density_score from CSV
# Output: hotspot_score, top N wards, zone summary

def detect_hotspots(ward_results: list, top_n: int = 5) -> dict:
    for w in ward_results:
        # z-score contribution (capped at 30 pts)
        z_contrib = min(max(w["z_score"] * 10, 0), 30)

        # density multiplier from CSV
        density_mult = w.get("density_score", 1) / 3  # normalize to 0–1

        w["hotspot_score"] = round(
            0.55 * w["outbreak_prob"] +
            0.25 * z_contrib +
            0.20 * density_mult * 100,
            2
        )

    ranked = sorted(ward_results, key=lambda x: x["hotspot_score"], reverse=True)

    return {
        "top_hotspots": ranked[:top_n],
        "all_ranked":   ranked,
        "zone_summary": {
            z: [w["ward"] for w in ward_results if w["zone"] == z]
            for z in ["RED", "YELLOW", "GREEN"]
        }
    }

# ═════════════════════════════════════════════════════════════
# MODEL 7 — Advisory Generator
# ═════════════════════════════════════════════════════════════
# Input:  zone, syndrome, hospital_load_pct, water_quality_issue, sanitation_score
# Output: prioritised list of advisories

SYNDROME_ADVISORIES = {
    "respiratory": [
        "Distribute N95 masks at PHCs in affected wards",
        "Screen for TB co-infection in prolonged fever cases",
        "Issue ventilation advisory for high-density housing",
    ],
    "vector_borne": [
        "Launch mosquito fogging operations in RED/YELLOW zones",
        "Issue water stagnation advisory — check coolers and containers",
        "Distribute mosquito nets and repellent at PHCs",
        "Activate rapid dengue/malaria test camps",
    ],
    "gastrointestinal": [
        "Test water supply quality — possible source contamination",
        "Distribute ORS and zinc packets at ward level",
        "Inspect food stalls, tiffin centres, and water tankers",
        "Coordinate with Pune Municipal Corporation for sanitation drive",
    ],
}

def generate_advisory(
    zone:               str,
    syndrome:           str,
    hospital_load_pct:  float,
    water_quality_issue: int  = 0,
    sanitation_score:   int  = 5,
) -> list:
    advisories = []

    # Zone-based actions
    if zone == "RED":
        advisories += [
            "[URGENT] Activate district outbreak response team",
            "[URGENT] Alert District Health Officer and CMO immediately",
            "Increase OPD capacity by 40% in affected wards",
            "Deploy field investigation teams within 24 hours",
            "Arrange emergency testing camps in high-density areas",
        ]
    elif zone == "YELLOW":
        advisories += [
            "Elevate monitoring to daily case review",
            "Pre-stock medications, ORS, and IV fluids at PHCs",
            "Prepare field teams for rapid deployment if escalation",
        ]
    else:
        advisories += [
            "Maintain weekly surveillance reporting",
        ]

    # Syndrome-specific
    advisories += SYNDROME_ADVISORIES.get(syndrome, [])

    # Hospital load
    if hospital_load_pct >= 85:
        advisories.append("[CAPACITY] Divert non-critical patients to secondary facilities immediately")
    elif hospital_load_pct >= 70:
        advisories.append("[CAPACITY] Review bed availability — load approaching critical threshold")

    # Water quality flag (from CSV)
    if water_quality_issue == 1:
        advisories.append("[WATER] Issue boil-water advisory for Ward area")

    # Sanitation risk
    if sanitation_score <= 4:
        advisories.append("[SANITATION] Fast-track sanitation inspection in low-scoring areas")

    return advisories

# ═════════════════════════════════════════════════════════════
# API FUNCTION — Return results as JSON for Node.js
# ═════════════════════════════════════════════════════════════

def get_outbreak_data():
    """Returns outbreak detection results in JSON format for API consumption"""
    df, DAY_COLS = load_ward_data()
    results = []

    for _, row in df.iterrows():
        cases = [int(row[d]) for d in DAY_COLS]

        # Model 4
        trends = analyze_trends(cases)

        # Model 5
        warning = outbreak_warning(row["ward"], cases)

        # Attach metadata
        warning["syndrome"]           = row["syndrome"]
        warning["hospital_load_pct"]  = float(row["hospital_load_pct"])
        warning["pmjay_coverage_pct"] = float(row["pmjay_coverage_pct"])
        warning["density_score"]      = int(row["density_score"])
        warning["water_quality_issue"]= int(row["water_quality_issue"])
        warning["sanitation_score"]   = int(row["sanitation_score"])
        warning["nearest_hospital_km"]= float(row["nearest_hospital_km"])
        warning["wow_growth_pct"]     = trends["wow_growth_pct"]
        warning["growth_48h_pct"]     = trends["growth_48h_pct"]
        warning["moving_avg_7d"]      = trends["moving_avg_7d"]
        warning["seasonality"]        = trends["seasonality"]

        # Generate advisories
        warning["advisories"] = generate_advisory(
            warning["zone"], warning["syndrome"], warning["hospital_load_pct"],
            warning["water_quality_issue"], warning["sanitation_score"]
        )

        results.append(warning)

    # Hotspot zoning
    hotspots = detect_hotspots(results)

    # Symptom clusters from `reports` table
    ward_names = df["ward"].tolist() if "ward" in df.columns else []
    top_symptoms, ward_symptoms = compute_symptom_aggregates(ward_names)

    return {
        "zone_summary": hotspots["zone_summary"],
        "top_hotspots": hotspots["top_hotspots"],
        "all_wards": hotspots["all_ranked"],
        "top_symptoms": top_symptoms,
        "ward_symptoms": ward_symptoms,
        "timestamp": str(pd.Timestamp.now())
    }

# ═════════════════════════════════════════════════════════════
# DEMO — Model 1, 2, 3 standalone examples
# ═════════════════════════════════════════════════════════════

def demo_patient_models():
    print("\n" + "═"*60)
    print("  PATIENT-LEVEL MODEL DEMOS")
    print("═"*60)

    # Model 1
    patient = {
        "symptoms":      {"cough": True, "breathlessness": True, "high_fever": True, "fatigue": True},
        "age":           65,
        "comorbidities": [True, False, True],   # diabetes, no asthma, heart disease
        "duration_days": 6,
    }
    sev = severity_score(patient["symptoms"], patient["age"], patient["comorbidities"], patient["duration_days"])
    print(f"\n▸ Model 1 — Severity Scoring")
    print(f"   Risk Score : {sev['risk_score']}/100")
    print(f"   Severity   : {sev['severity']}")

    # Model 2
    pq = priority_index(sev["risk_score"], patient["age"], days_waiting=2)
    print(f"\n▸ Model 2 — Priority Queue")
    print(f"   Priority Index : {pq['priority_index']}")
    print(f"   Queue Label    : {pq['queue_label']}")

    # Model 3
    patient_for_hosp = {"needed_specialty": "respiratory", "pmjay_beneficiary": True}
    recs = recommend_hospitals(patient_for_hosp)
    print(f"\n▸ Model 3 — Hospital Recommendations")
    for r in recs:
        print(f"   {r['hospital']:<35} Score: {r['score']}  PM-JAY: {r['pmjay']}  Free beds: {r['beds_free']}")

# ═════════════════════════════════════════════════════════════
# ENTRY POINT
# ═════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys
    import json

    if len(sys.argv) > 1 and sys.argv[1] == "--get-data":
        # API mode - output JSON
        try:
            data = get_outbreak_data()
            print(json.dumps(data))
        except Exception as e:
            print(json.dumps({"error": str(e)}))
    else:
        # Demo mode
        result_df = run_pipeline()
        demo_patient_models()

        # Optional: export results
        result_df.drop(columns=["advisories"]).to_csv("pipeline_results.csv", index=False)
        print("\n\n  Results exported to pipeline_results.csv")